baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Hugo Learn Documentation"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = false

[params]
  editURL = "https://github.com/Salix-OS/docs.salixos.org"
  description = "Salix Documentation"
  author = "George Vlahavas"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = true
  disableLanguageSwitchingButton = true
  themeVariant = "green"
  disableInlineCopyToClipBoard = true


[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fas fa-home'></i> Main website"
identifier = "ds"
url = "https://salixos.org"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-question-circle'></i> Support Forum"
url = "https://forum.salixos.org"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-blog'></i> Blog"
url = "https://blog.salixos.org"
weight = 30
